# Generated by Django 5.0.2 on 2024-02-18 12:06

from django.db import migrations

from users.utils import constants


def add_client_role(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name=constants.CLIENT_GROUP_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_client_role),
    ]
