# Generated by Django 5.0.2 on 2024-02-18 14:41

from django.db import migrations

from users.utils import constants


def add_operator_role(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name=constants.OPERATOR_GROUP_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_client_role"),
    ]

    operations = [
        migrations.RunPython(add_operator_role),
    ]
